### PR TITLE
Build inside docker

### PR DESCRIPTION
**Pull request by yangcha**
Build gettext inside a docker container.

### CODE REVIEW

**Comment by mlocati** [comment]
What about simply adding to the readme a section like this?

```md
## Running in docker

You can build the gettext/iconv binaries inside docker.
Just clone this repository, open a terminal and run this command:

- Linux/Mac:
    ```sh
    docker run --rm -it -v "$PWD:/app mlocati/gettext-iconv-windows:latest" /app/compile-iconv-gettext-windows.sh
    ```
- Windows
    ```bat
    docker run --rm -it -v "%CD%:/app" mlocati/gettext-iconv-windows:latest /app/compile-iconv-gettext-windows.sh
    ```
```

**Comment by yangcha** [comment]
That will be great.

**Comment by yangcha** [comment]
> What about simply adding to the readme a section like this?
> 
> ```lisp
> ## Running in docker
> 
> You can build the gettext/iconv binaries inside docker.
> Just clone this repository, open a terminal and run this command:
> 
> - Linux/Mac:
>     ```sh
>     docker run --rm -it -v "$PWD:/app mlocati/gettext-iconv-windows:latest" /app/compile-iconv-gettext-windows.sh
>     ```
> - Windows
>     ```bat
>     docker run --rm -it -v "%CD%:/app" mlocati/gettext-iconv-windows:latest /app/compile-iconv-gettext-windows.sh
>     ```
> ```

That will be great.

**Comment by mlocati** [comment]
The docker image is ready to be used: see https://github.com/mlocati/gettext-iconv-windows/#building-with-docker

(and thanks for the nice idea!)

**Pull request closed without merging**
