### PR TITLE
Build libintl with static libgcc

### LINKED ISSUE #8: Remove dependency on libgcc_s_sjlj-1.dll for 32bit versions
As we discussed in vim/vim-win32-installer#20 (and #7), `libintl-8.dll` has dependency on `libgcc_s_sjlj-1.dll`.
I thought the dependency should be able to be removed by adding `-static-libgcc`, but it didn't work, as you know.

I installed your build script (with mxe) and after doing some trials, I found the cause of the issue: The `libtool` script stripped the `-static-libgcc` option.

When I edited the Makefile for `libintl-8.dll` as follows, the dependency was successfully removed:

```diff
--- build-gettext-windows/shared-32/configured/gettext-0.19.8.1/gettext-runtime/intl/Makefile.org
+++ build-gettext-windows/shared-32/configured/gettext-0.19.8.1/gettext-runtime/intl/Makefile
@@ -108,7 +108,7 @@
 LDFLAGS = -L/home/ken/build-gettext-windows/shared-32/compiled/gettext/lib -Wl,--disable-auto-import $(LDFLAGS_yes)
 LDFLAGS_yes = -Wl,--export-all-symbols
 LDFLAGS_no =
-LIBS = 
+LIBS = -XCClinker -static-libgcc
 
 COMPILE = $(CC) -c $(DEFS) $(INCLUDES) $(CPPFLAGS) $(CFLAGS) $(XCFLAGS)
 
```
`-XCClinker` is the option for libtool for passing the following flag to the compiler driver.

I don't know how I can apply this change into your build script, but could you consider applying this?

### PR DESCRIPTION
**Pull request by mlocati**
Fix #8

### CODE REVIEW

**Comment by k-takata** [comment]
Didn't  you merge this into the latest release (gettext 0.20 + iconv 1.16)?

**Comment by mlocati** [comment]
@k-takata The static versions don't have any DLL dependency. Can't you just use them?

**Comment by k-takata** [comment]
I need libiconv-2.dll and libintl-8.dll, not the exe files.
I also found that libintl-8.dll was renamed to libintl-7.dll. Why?

**Comment by mlocati** [comment]
> I need libiconv-2.dll and libintl-8.dll, not the exe files.

Gotcha.

> I also found that libintl-8.dll was renamed to libintl-7.dll. Why?

I absolutely don't know. You should ask to the bug-gettext@gnu.org mailing list (see https://lists.gnu.org/mailman/listinfo/bug-gettext).

**Comment by mlocati** [comment]
Let's keep talking about this at #8

**Pull request closed without merging**
